### ISSUE TITLE
filter presented black cards by gender-preference

### ISSUE THREAD

**Issue by JoMuelle** [sopra-fs22-group-07/server#134]
- related to #129 
- dependent on #157

only allowing black cards from Players who match the Playing users preferences (while the playing user also matches the preferences of the black cards player)

**Comment by daveking7** [comment]
@JoMuelle 
![image](https://user-images.githubusercontent.com/75019468/166679575-de1c095d-5f5f-4ad1-8549-6596e04e12c8.png)
or similar should do the job
