### ISSUE TITLE
When a user is blocked their black cards don’t show up for the other user anymore

### ISSUE THREAD

**Issue by JoMuelle** [sopra-fs22-group-07/server#155]
see #129

**Comment by daveking7** [comment]
When a user is unmatched, It shall be possible to match with that user again. Otherwise, the block-feature would be useless.

**Comment by daveking7** [comment]
![image](https://user-images.githubusercontent.com/75019468/168393279-0c80e375-2840-4c2a-95b3-915905ec8dbb.png)
You have just to update this query, the rest is done
@anhuwi

**Comment by anhuwi** [comment]
changed it, but i have to test it
