### ISSUE TITLE
Adding two matches does not work

### ISSUE THREAD

**Issue by TwoDigitsOneNumber** [sopra-fs22-group-07/server#166]
How the bug was found:
when adding demo users (manually by calling the functions in the userService.instantiateDemoUsers) a JPA primary key violation (see https://github.com/sopra-fs22-group-07/server/pull/153#discussion_r864782700)

To be tested: does this also occur when generating matches through the frontend or is this a result of creating them manually in the backend?

**Comment by daveking7** [comment]
> To be tested: does this also occur when generating matches through the frontend or is this a result of creating them manually in the backend?

@TwoDigitsOneNumber Don't see how this would have anything todo with the frontend, albeit being the caller.
